import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './global.css';
import NavBar from "@/components/NavBar/NavBar";
import Header from "@/components/Header/Header";




const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "GB adviser",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="wrapper">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
